[build]
  publish = "frontend/"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[functions]
  directory = "functions"

[functions.http_headers]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Headers = "Content-Type"